config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users
  get 'animals/new'
  get 'pages/home'
  get 'animals/details'

  post 'animals' => 'animals#create'
  post 'comments' => 'comments#create'
  root 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :user
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_one :adoption
  has_many :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :animal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :adoptions
  has_many :comments
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  Time::DATE_FORMATS[:post] = "-- %d/%b/%Y - %I:%M%p"

  def new
      @animal = Animal.new

  end


  def create
    @animal = Animal.new(get_animal_params)

    if @animal.save
      redirect_to root_path
    end

  end

  def details
    @animal = Animal.find(get_id_param)
    @adopt = authenticate

    @comment = Comment.new
    @comments = Comment.all
    @user = User.all
  end

  private
     def authenticate
       if user_signed_in?
         true
       else
         false
       end
     end

    def get_animal_params
      @params = params.require(:animal).permit(:nick, :kind, :color, :weight, :description)
    end

    def get_id_param
      @param = params.require(:id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #autenticar antes de ação menos na home
  before_action :authenticate_user!, except: [:home,:details]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @comment = Comment.new(get_params)
    @comment.user_id = current_user.id

    @comment.save

    redirect_back(fallback_location: root_path)

  end

  private
    def get_params
      params.require(:comment).permit(:message,:animal_id)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
    @animals=Animal.all
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/animals/details.html.erb
<div class=" w3-row w3-container w3-white w3-padding w3-round-xlarge my-wrap-large" >
  <img class="w3-col l8 m7 " src="/dog.jpg" style="max-width:600px;max-height:450px;"></img>

  <div class="w3-col l4 m5 w3-container my-beje w3-round w3-card-4" style="display:inline-block;margin-bottom:10px">
    <label>Nick</label>
    <p><%= @animal.nick %></p>
    <label>Weight</label>
    <p><%= @animal.weight %></p>
    <label>Kind</label>
    <p><%= @animal.kind %></p>
    <label>Color</label>
    <p><%= @animal.color %></p>
    <label>Description</label>
    <p><%= @animal.description %></p>
  </div>

  <div class="w3-col l4 w3-center ">
    <% if @adopt %>
      <button class="w3-button w3-xlarge w3-green">Adotar !</button>
    <% else %>
      <button class="w3-button w3-xlarge w3-green">Logar !</button>
    <% end %>
  </div>

  <div class="w3-row" style="margin-bottom:5px;">
    <p>Comentarios</p>
    <% @comments.each do |c| %>
      <% if c.animal_id == @animal.id %>
        <div class="w3-col l12 w3-round-large w3-col l12 w3-container w3-blue my-margin-6">
          <p><%= c.message %></p>
          <p class="w3-right w3-small"><%= c.created_at.to_s(:post) %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="w3-container">
    <%= simple_form_for @comment do |c| %>
      <%= c.input :message, label: false %>
      <%= c.hidden_field :animal_id, :value => @animal.id %>
      <%= c.submit 'Enviar', class: 'w3-button w3-border' %>
    <% end %>
  </div>


</div>

app/views/animals/new.html.erb
<div class="my-wrap-large w3-white w3-round-xlarge w3-hide-small">
  <%= simple_form_for @animal do |form| %>
    <%= form.input :nick, label: 'Apelido' %>
    <%= form.input :kind, label: 'Tipo do bixo' %>
    <%= form.input :color, label: 'Cor' %>
    <%= form.input :weight, label: 'Peso' %>
    <%= form.input :description, label: 'Descrição' %>

    <%= form.submit 'Cadastrar', class:'w3-button w3-green w3-round-large' %>
  <% end %>
</div>

<div class="my-wrap-small w3-white w3-round-xlarge w3-hide-large w3-hide-medium">
  <%= simple_form_for @animal do |form| %>
    <%= form.input :nick, label: 'Apelido' %>
    <%= form.input :kind, label: 'Tipo do bixo' %>
    <%= form.input :color, label: 'Cor' %>
    <%= form.input :weight, label: 'Peso' %>
    <%= form.input :description, label: 'Descrição' %>

    <%= form.submit 'Cadastrar', class:'w3-button w3-green w3-round-large' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color:#c5ddff;">
  <head>
    <title>RunDownPuppy</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <sidebar class="w3-sidebar w3-bar-block w3-hide-large w3-card w3-animate-right w3-display-right my-sidebar" onload="w3_start" id="mySidebar">
      <div class=" w3-bar-item" style="margin-top:50px;"></div>

      <button class="w3-bar-item w3-button w3-large w3-border-bottom w3-border-black" onclick="w3_close()">Fechar &times;</button>

      <%= link_to "Histórico", root_path, class:'w3-bar-item w3-button w3-small w3-mobile' %>
      <%= link_to "Cadastrar", animals_new_path, class:' w3-bar-item w3-button w3-mobile w3-purple w3-small' %>

      <% if user_signed_in? %>
      <button class="w3-bar-item w3-button w3-xlarge my-black"><%= link_to'Logado', root_path, class:'my-black' %> <spam class="w3-badge w3-white">O</spam></button>
      <% else %>
        <%= link_to "Login", new_user_session_path, class:'w3-bar-item w3-button w3-green w3-xlarge w3-mobile ' %>
      <%end%>


    </sidebar>

    <div class="w3-main my-back-color">
      <div class="w3-top">
        <div class="w3-bar w3-animate-top my-bar " >

            <%= link_to root_path, class:'w3-bar-item ' do %>
              <h1 class="w3-wide w3-large">RunDownPuppy</h1>
            <% end %>

            <div class="w3-display-middle">
              <form method="POST" action="#">
              <input id="mySearch" type="search" class="w3-bar-item  w3-input w3-white w3-hide-medium w3-hide-small" placeholder="Buscar.."/>
              <input type="submit" class="w3-bar-item w3-button w3-green w3-mobile w3-hide-medium w3-hide-small" value="Go"/>
             </form>
            </div>

            <div  id="myMenu" class="w3-hide-small w3-hide-medium w3-display-right w3-bar-item my-letter">
              <%= link_to 'Histórico', root_path , class:'w3-bar-item w3-button w3-xlarge my-letter' %>
              <% if user_signed_in? %>
                <button class="w3-bar-item w3-button w3-xlarge my-letter"><%= link_to'Logado', root_path, class:'my-letter' %> <spam class="w3-badge w3-white">O</spam></button>
              <% else %>
                <%= link_to 'Login', new_user_session_path , class:'w3-button w3-green w3-xlarge' %>
              <% end %>
            </div>

            <button class="w3-button w3-xlarge w3-hide-large w3-bar-item w3-right"  id="myButton" onclick="w3_open()">&#9776;</button>
            <button onclick="w3_search()" class="w3-padding w3-right w3-xxlarge w3-bar-item w3-hide-large w3-button"><i class="fa fa-search"></i></button>
        </div>
      </div>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="w3-container w3-padding-32 w3-display-center my-back">
  <div class="w3-col l11 w3-center" >

    <% @animals.each do |a| %>
      <div class="w3-btn my-item">
        <%= link_to(animals_details_path id: a.id)  do %>
            <img class="animal-thumb" src="/dog.jpg"></img>
            <div class="w3-container w3-padding my-nick"><%= a.nick %></div>
        <% end %>
      </div>

    <% end %>


  </div>

    <div style="margin-top:10px;">

        <%= link_to 'CADASTRAR', animals_new_path , class:'w3-button w3-mobile w3-green  w3-block' %>

    </div>
</div>